### ISSUE TITLE
1.0.1 추가

### ISSUE THREAD

**Issue by LoveHoly** [LoveHoly/AccusationLite#1]
- Progress Bar 표시
- 여러개 URL 처리 기능 추가

**Comment by LoveHoly** [comment]
https://twitter.com/marribbong/status/990518893297876992

**Comment by EcmaXp** [comment]
window on top

**Comment by LoveHoly** [comment]
@EcmaXp 계획없음

**Comment by LoveHoly** [comment]
1.0.1 버전 업 완료. 릴리즈를 확인하세요.
